version: "3"
services:
        drupal:
                container_name: drupal
                image: custom-rupal
                build:
                        context: .
                ports:
                        - "8080:80"
                volumes:
                        - drupal_modules:/var/www/html/modules
                        - drupal_profiles:/var/www/html/profiles
                        - drupal_sites:/var/www/html/sites
                        - drupal_themes:/var/www/html/themes
        postgres:
                container_name: postgres
                image: postgres:12.1
                environment:
                        POSTGRES_PASSWORD: postgres
                volumes:
                        - drupal-data:/var/lib/postgresql/data

volumes:
        drupal-data:
        drupal_modules:
        drupal_profiles:
        drupal_sites:
        drupal_themes:
